name: inoutfusion
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.9.9
  - expat=2.7.1
  - libffi=3.4.4
  - libzlib=1.3.1
  - openssl=3.0.18
  - pip=25.2
  - python=3.9.23
  - setuptools=80.9.0
  - sqlite=3.50.2
  - tk=8.6.15
  - tzdata=2025b
  - ucrt=10.0.22621.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - certifi==2025.10.5
      - charset-normalizer==3.4.3
      - colorama==0.4.6
      - complexpytorch==0.4
      - einops==0.8.1
      - filelock==3.13.1
      - fsspec==2024.6.1
      - huggingface-hub==0.35.3
      - idna==3.11
      - jinja2==3.1.4
      - markupsafe==2.1.5
      - mpmath==1.3.0
      - networkx==3.2.1
      - numpy==2.0.2
      - opencv-python-headless==4.12.0.88
      - packaging==25.0
      - pillow==11.0.0
      - pyyaml==6.0.3
      - requests==2.32.5
      - safetensors==0.6.2
      - scipy==1.13.1
      - simpleitk==2.5.2
      - sympy==1.13.1
      - timm==1.0.20
      - torch==2.5.1+cu121
      - torchaudio==2.5.1+cu121
      - torchvision==0.20.1+cu121
      - tqdm==4.67.1
      - typing-extensions==4.12.2
      - urllib3==2.5.0
